<?php

echo "";
echo "<body>";
echo "    <!-- Start Top Nav -->";
echo "    <nav class='navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block' id='templatemo_nav_top'>";
echo "        <div class='container text-light'>";
echo "            <div class='w-100 d-flex justify-content-between'>";
echo "                <div>";
echo "                    <i class='fa fa-envelope mx-2'></i>";
echo "                    <a class='navbar-sm-brand text-light text-decoration-none' href='mailto:info@company.com'>info@company.com</a>";
echo "                    <i class='fa fa-phone mx-2'></i>";
echo "                    <a class='navbar-sm-brand text-light text-decoration-none' href='tel:010-020-0340'>010-020-0340</a>";
echo "                </div>";
echo "                <div>";
echo "                    <a class='text-light' href='https://fb.com/templatemo' target='_blank' rel='sponsored'><i class='fab fa-facebook-f fa-sm fa-fw me-2'></i></a>";
echo "                    <a class='text-light' href='https://www.instagram.com/' target='_blank'><i class='fab fa-instagram fa-sm fa-fw me-2'></i></a>";
echo "                    <a class='text-light' href='https://twitter.com/' target='_blank'><i class='fab fa-twitter fa-sm fa-fw me-2'></i></a>";
echo "                    <a class='text-light' href='https://www.linkedin.com/' target='_blank'><i class='fab fa-linkedin fa-sm fa-fw'></i></a>";
echo "                </div>";
echo "            </div>";
echo "        </div>";
echo "    </nav>";
echo "    <!-- Close Top Nav -->";
echo "";
echo "";
echo "    <!-- Header -->";
echo "    <nav class='navbar navbar-expand-lg navbar-light shadow'>";
echo "        <div class='container d-flex justify-content-between align-items-center'>";
echo "";
echo "            <a class='navbar-brand text-success logo h1 align-self-center' href='index.php'>";
echo "                Gadzo";
echo "            </a>";
echo "";
echo "            <button class='navbar-toggler border-0' type='button' data-bs-toggle='collapse' data-bs-target='#templatemo_main_nav' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>";
echo "                <span class='navbar-toggler-icon'></span>";
echo "            </button>";
echo "";
echo "            <div class='align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between' id='templatemo_main_nav'>";
echo "                <div class='flex-fill'>";
echo "                    <ul class='nav navbar-nav d-flex justify-content-between mx-lg-auto'>";
echo "                        <li class='nav-item'>";
echo "                            <a class='nav-link' href='../../index.php'>Home</a>";
echo "                        </li>";
echo "                        <li class='nav-item'>";
echo "                            <a class='nav-link' href='../../about.php'>About</a>";
echo "                        </li>";
echo "                        <li class='nav-item'>";
echo "                            <a class='nav-link' href='../../shop.php'>Shop</a>";
echo "                        </li>";
echo "                        <li class='nav-item'>";
echo "                            <a class='nav-link' href='../../contact.php'>Contact</a>";
echo "                        </li>";
echo "                    </ul>";
echo "                </div>";
echo "                <div class='navbar align-self-center d-flex'>";
echo "                    <div class='d-lg-none flex-sm-fill mt-3 mb-4 col-7 col-sm-auto pr-3'>";
echo "                        <div class='input-group'>";
echo "                            <input type='text' class='form-control' id='inputMobileSearch' placeholder='Search ...'>";
echo "                            <div class='input-group-text'>";
echo "                                <i class='fa fa-fw fa-search'></i>";
echo "                            </div>";
echo "                        </div>";
echo "                    </div>";
echo "                    <a class='nav-icon d-none d-lg-inline' href='#' data-bs-toggle='modal' data-bs-target='#templatemo_search'>";
echo "                        <i class='fa fa-fw fa-search text-dark mr-2'></i>";
echo "                    </a>";
echo "                    <a class='nav-icon position-relative text-decoration-none' href='#'>";
echo "                        <i class='fa fa-fw fa-cart-arrow-down text-dark mr-1'></i>";
echo "                        <span class='position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark'>7</span>";
echo "                    </a>";
echo "                    <a class='nav-icon position-relative text-decoration-none' href='#'>";
echo "                        <i class='fa fa-fw fa-user text-dark mr-3'></i>";
echo "                        <span class='position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark'>+99</span>";
echo "                    </a>";
echo "                </div>";
echo "            </div>";
echo "";
echo "        </div>";
echo "    </nav>";
echo "    <!-- Close Header -->";

echo "		<!-- Modal -->";
echo "		<div class='modal fade bg-white' id='templatemo_search' tabindex='-1' role='dialog' aria-labelledby='exampleModalLabel' aria-hidden='true'>";
echo "			<div class='modal-dialog modal-lg' role='document'>";
echo "				<div class='w-100 pt-1 mb-5 text-right'>";
echo "					<button type='button' class='btn-close' data-bs-dismiss='modal' aria-label='Close'></button>";
echo "				</div>";
echo "				<form action='' method='get' class='modal-content modal-body border-0 p-0'>";
echo "					<div class='input-group mb-2'>";
echo "						<input type='text' class='form-control' id='inputModalSearch' name='q' placeholder='Search ...'>";
echo "						<button type='submit' class='input-group-text bg-success text-light'>";
echo "							<i class='fa fa-fw fa-search text-white'></i>";
echo "						</button>";
echo "					</div>";
echo "				</form>";
echo "			</div>";
echo "		</div>";

?>